[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tloader.x",
    "-C", "link-args=-Map=starfive-loader.map",
    "-C", "link-args=--nmagic",
]

[build]
target = "riscv64gc-unknown-none-elf"
